// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/minh1611/clinics_chain_management/authservice/src/internal/api"
	"github.com/minh1611/clinics_chain_management/authservice/src/internal/db"
	"github.com/minh1611/clinics_chain_management/authservice/src/internal/db/my"
	"github.com/minh1611/clinics_chain_management/authservice/src/internal/model"
)

// Injectors from server.wire.go:

func InitMainServer(ctx context.Context, opts ServerOptions) (*Server, error) {
	dbDsn := opts.DBDsn
	gormDB, err := db.ConnectGorm(dbDsn)
	if err != nil {
		return nil, err
	}
	dbInterfaces := my.InterfaceProvider()
	serverCDBRepo := &my.ServerCDBRepo{
		Db:         gormDB,
		Context:    ctx,
		Interfaces: dbInterfaces,
	}
	serverModel := &model.ServerModel{
		Ctx:  ctx,
		Repo: serverCDBRepo,
	}
	apiServer := &api.ApiServer{
		Model: serverModel,
		Repo:  serverCDBRepo,
	}
	server := &Server{
		ApiServer: apiServer,
		MainRepo:  serverCDBRepo,
	}
	return server, nil
}

// server.wire.go:

type Server struct {
	ApiServer *api.ApiServer
	MainRepo  db.ServerRepo
}

type ServerOptions struct {
	DBDsn db.DBDsn
}
